# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  olivier.uk:
    site_hosts:
      - canonical: olivier.test
        redirects:
          - www.olivier.test
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_user: olivier
    admin_email: olivier@olivier.uk
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    site_title: Olivier.uk
